Fix usage of semver, update CI test matrix
meteor/reify pull request #5
Opened 2024-05-04 07:29 UTC by perbergland

Adapts the semver code to not crash
Updates list of nodejs versions for CI tests to reasonable values in 2024

2024-05-04 12:01 UTC, StorytellerCZ requested changes

2024-05-04 12:01 UTC, StorytellerCZ commented on .github/workflows/node.js.yml
> +        node-version: [14.x, 16.x, 18.x, 20.x, 21.x]
Instead of 21, you can now use 22.

2024-05-04 12:31 UTC, StorytellerCZ approved these changes

2024-06-17 13:23 UTC, closed without merging

2024-06-17 13:23 UTC, leonardoventurini commented
https://github.com/meteor/reify/pull/8